# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x05model\"\x07\n\x05\x45mpty\"\x1d\n\x0bModelStatus\x12\x0e\n\x06status\x18\x01 \x01(\t\" \n\rTrainResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2o\n\x0cModelService\x12-\n\tGetStatus\x12\x0c.model.Empty\x1a\x12.model.ModelStatus\x12\x30\n\nTrainModel\x12\x0c.model.Empty\x1a\x14.model.TrainResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_MODELSTATUS']._serialized_start=31
  _globals['_MODELSTATUS']._serialized_end=60
  _globals['_TRAINRESPONSE']._serialized_start=62
  _globals['_TRAINRESPONSE']._serialized_end=94
  _globals['_MODELSERVICE']._serialized_start=96
  _globals['_MODELSERVICE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
